name: Deploy or Validate the project to Salesforce

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose Action: Sandbox, Production, or Validate Only"
        required: true
        default: "Sandbox"
        type: choice
        options:
          - Sandbox
          - Production
          - Validate Only

jobs:
  deploy-or-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global

      - name: Authenticate to Salesforce (device login)
        run: |
          if [ "${{ github.event.inputs.environment }}" == "Production" ]; then
            echo "Authenticating to Production..."
            sfdx force:auth:device:login -d -a prod -r https://login.salesforce.com
          elif [ "${{ github.event.inputs.environment }}" == "Sandbox" ]; then
            echo "Authenticating to Sandbox..."
            sfdx force:auth:device:login -d -a sandbox -r https://test.salesforce.com
          else
            echo "Validate Only selected. Authenticating to Sandbox for validation..."
            sfdx force:auth:device:login -d -a sandbox -r https://test.salesforce.com
          fi

      - name: Perform Action: Validate or Deploy
        run: |
          if [ "${{ github.event.inputs.environment }}" == "Production" ]; then
            echo "Deploying to Production..."
            sfdx force:source:deploy -p force-app -u prod --testlevel NoTestRun
          elif [ "${{ github.event.inputs.environment }}" == "Sandbox" ]; then
            echo "Deploying to Sandbox..."
            sfdx force:source:deploy -p force-app -u sandbox --testlevel NoTestRun
          else
            echo "Running Validate Only (dry-run) in Sandbox..."
            sfdx force:source:deploy -p force-app -u sandbox --checkonly --testlevel NoTestRun
          fi
