name: Deploy or Validate to Salesforce

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose Action - Sandbox, Production, or Validate Only"
        required: true
        default: "Sandbox"
        type: choice
        options:
          - Sandbox
          - Production
          - Validate Only

jobs:
  deploy:
    name: Salesforce Deployment or Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global

      - name: Authenticate based on selected environment
        run: |
          case "${{ github.event.inputs.environment }}" in
            "Production")
              echo "Authenticating to Production..."
              sfdx force:auth:device:login -d -a prod -r https://login.salesforce.com
              ;;
            "Sandbox"|"Validate Only")
              echo "Authenticating to Sandbox..."
              sfdx force:auth:device:login -d -a sandbox -r https://test.salesforce.com
              ;;
          esac

      - name: Run Validate or Deploy
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "Validate Only" ]]; then
            echo "Validating only (dry-run)..."
            sfdx force:source:deploy -p force-app -u sandbox --checkonly --testlevel NoTestRun
          elif [[ "${{ github.event.inputs.environment }}" == "Production" ]]; then
            echo "Deploying to Production..."
            sfdx force:source:deploy -p force-app -u prod --testlevel NoTestRun
          else
            echo "Deploying to Sandbox..."
            sfdx force:source:deploy -p force-app -u sandbox --testlevel NoTestRun
          fi
