name: Salesforce Deploy / Validate Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action to perform"
        required: true
        default: "Deploy to Sandbox"
        type: choice
        options:
          - Deploy to Sandbox
          - Deploy to Production
          - Validate in Sandbox
          - Validate in Production

jobs:
  deploy-or-validate:
    name: Salesforce: ${{ github.event.inputs.action }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global

      - name: Authenticate to Salesforce Org
        run: |
          case "${{ github.event.inputs.action }}" in
            "Deploy to Production"|"Validate in Production")
              echo "Authenticating to Production..."
              sfdx force:auth:device:login -d -a prod -r https://login.salesforce.com
              ;;
            "Deploy to Sandbox"|"Validate in Sandbox")
              echo "Authenticating to Sandbox..."
              sfdx force:auth:device:login -d -a sandbox -r https://test.salesforce.com
              ;;
          esac

      - name: Execute Action
        run: |
          ACTION="${{ github.event.inputs.action }}"
          USER_ALIAS=$( [[ "$ACTION" =~ Production ]] && echo "prod" || echo "sandbox" )

          if [[ "$ACTION" == "Deploy to Sandbox" || "$ACTION" == "Deploy to Production" ]]; then
            echo "Deploying to $USER_ALIAS..."
            sfdx force:source:deploy -p force-app -u "$USER_ALIAS" --testlevel NoTestRun
          else
            echo "Validating in $USER_ALIAS (check-only)..."
            sfdx force:source:deploy -p force-app -u "$USER_ALIAS" --checkonly --testlevel NoTestRun
          fi
